spring:
  application:
    name: spot-store
  config:
    import:
      # bootRun
      - optional:file:../config/common.yml
      - optional:file:../config/kafka-topics.yml
      - optional:file:../config/application-secret.yml
      - optional:file:../config/spot-store.yml

      # docker-compose
      - optional:file:/config/common.yml
      - optional:file:/config/spot-store.yml
      - optional:file:/config/application-secret.yml