spring:
  application:
    name: spot-store
  config:
    import:
      # bootRun
      # bootRun
      - optional:classpath:/common.yml
      - optional:classpath:/kafka-topics.yml
      - optional:classpath:/spot-store.yml

      # docker-compose
      - optional:file:/config/common.yml
      - optional:file:/config/kafka-topics.yml
      - optional:file:/config/spot-store.yml