spring:
  application:
    name: spot-order
  config:
    import:
      # bootRun
      - optional:classpath:/common.yml
      - optional:classpath:/kafka-topics.yml
      - optional:classpath:/spot-order.yml

      # docker-compose
      - optional:file:/config/common.yml
      - optional:file:/config/kafka-topics.yml
      - optional:file:/config/spot-order.yml