spring:
  application:
    name: spot-user
  config:
    import:
      - optional:classpath:/application-secret.yml
      - optional:classpath:/common.yml
      - optional:classpath:/kafka-topics.yml
      - optional:classpath:/spot-user.yml

      - optional:file:/config/common.yml
      - optional:file:/config/spot-user.yml
      - optional:file:/config/application-secret.yml