spring:
  config:
    import: 
      - file:/config/common.yml
      - file:/config/kafka-topics.yml
  application:
    name: spot-payment
  kafka:
    consumer:
      group-id: payment-group
    
server:
  port: 8084
