spring:
  config:
    import: 
      - file:/config/common.yml
      - file:/config/kafka-topics.yml
  application:
    name: spot-order
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: order-group
      auto-offset-reset: earliest

server:
  port: 8082
