spring:
  config:
    import: optional:classpath:common-application.yml
  application:
    name: spot-payment

server:
  port: 8084


feign:
  store:
    base-url: http://spot-store:8083
  payment:
    base-url: http://spot-payment:8084
  client:
    config:
      spot-store:
        connectTimeout: 100
        readTimeout: 600
        loggerLevel: BASIC
      spot-payment:
        connectTimeout: 100
        readTimeout: 700
        loggerLevel: BASIC

resilience4j:
  retry:
    instances:
      store_me_ownership:
        maxAttempts: 1
        waitDuration: 0ms
      store_menus_validation:
        maxAttempts: 2
        waitDuration: 50ms
        retryExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - feign.RetryableException
      payment_ready_create:
        maxAttempts: 1
        waitDuration: 0ms

  circuitbreaker:
    configs:
      cb_failureRate_short:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - feign.RetryableException
          - feign.FeignException

      cb_slowCall_short:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 300ms
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
          - feign.RetryableException
          - feign.FeignException

    instances:
      store_me_ownership:
        baseConfig: cb_failureRate_short
      store_menus_validation:
        baseConfig: cb_slowCall_short
      payment_ready_create:
        baseConfig: cb_slowCall_short

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.example.Spot: INFO
    feign: INFO
    io.github.resilience4j.circuitbreaker: INFO
    io.github.resilience4j.retry: INFO
    io.github.resilience4j.bulkhead: INFO