spring:
  config:
    import: 
      - file:/config/common.yml
      - file:/config/kafka-topics.yml
  application:
    name: spot-order
  kafka:
    consumer:
      group-id: order-group
      
server:
  port: 8082
