spring:
  config:
    import: file:/config/common.yml
  application:
    name: spot-user

server:
  port: 8081

feign:
  order:
    url: http://spot-order:8083
  store:
    url: http://spot-store:8082
  payment:
    url: http://spot-payment:8084
