spring:
  config:
    import: file:/config/common.yml
  application:
    name: spot-payment
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
    
server:
  port: 8084
