name: DEV PR Check - Test

on:
  push:
    branches: [ refactor/304-git ]

jobs:
  call-template:
    uses: "./.github/workflows/_common-dev-pr-check.yml"
    with:
      service-name: "test"
      working-directory: 'spot-payment'