name: DEV PR Check - GateWay

on:
  pull_request:
    branches: [ dev ]
    paths:
      - 'config/spot-gateway.yml'
      - 'spot-gateway/**'
      - '.github/workflows/dev-pr-check-gateway.yml'

jobs:
  call-common:
    uses: ./.github/workflows/_common-dev-pr-check.yml
    with:
      service-name: spot-gateway
      working-directory: spot-gateway
      health-port: 8080